# Generated by Django 3.2.6 on 2021-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
